version: '2'
services:
    totoscheduler-app:
        image: totoscheduler
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://totoscheduler-postgresql:5432/TotoScheduler
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    totoscheduler-postgresql:
        extends:
            file: postgresql.yml
            service: totoscheduler-postgresql
